import { Geist, Geist_Mono, Play } from 'next/font/google';
import { Playfair_Display, Inter, Quicksand, Mulish } from 'next/font/google';
import './globals.css';

const geistSans = Quicksand({
  variable: '--font-playful-display',
  subsets: ['latin'],
});

const geistMono = Mulish({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Recipe Nest',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
