import { Geist, Geist_Mono, Play } from 'next/font/google';
import {
  Playfair_Display,
  Inter,
  Quicksand,
  Mulish,
  Edu_NSW_ACT_Cursive,
  Lato,
} from 'next/font/google';
import './globals.css';

const geistSans = Quicksand({
  variable: '--font-playful-display',
  subsets: ['latin'],
});

const geistMono = Mulish({
  variable: '--font-inter',
  subsets: ['latin'],
});

const eduCursive = Edu_NSW_ACT_Cursive({
  variable: '--font-cursive',
  subsets: ['latin'],
});

const lato = Lato({
  variable: '--font-lato',
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Recipe Nest',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${eduCursive.variable} ${lato.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
